eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka/
server:
  port: 8989
spring:
  application:
    name: shopping-gateway
zuul:
  routes:
    api-manager:
      path: /shopping-manager/**
      service-id: shopping-sellergoods-ms
    api-content:
      path: /shopping-content/**
      service-id: shopping-content-ms
    api-search:
      path: /shopping-search/**
      service-id: shopping-search-ms
    api-page:
      path: /shopping-page/**
      service-id: shopping-page-ms

ribbon:
  ConnectTimeout: 5000 # 连接超时时间(ms)
  ReadTimeout: 5000 # 通信超时时间(ms)
hystrix:
  command:
    default:
    execution:
    isolation:
    thread:
    timeoutInMilliseconds: 60000 # 设置hystrix的超时时间为6000ms