eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka/
server:
  port: 8989
spring:
  application:
    name: shopping-gateway
zuul:
  routes:
    api-manager:
      path: /shopping-manager/**
      service-id: shopping-sellergoods-ms
    api-content:
      path: /shopping-content/**
      service-id: shopping-content-ms
    api-search:
      path: /shopping-content/**
      service-id: shopping-content-ms
    api-page:
      path: /shopping-page/**
      service-id: shopping-page-ms
    