server:
  port: 8801
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka
spring:
  data:
    solr:
      host: http://127.0.0.1:8080/solr
  application:
    name: 'shopping-search-ms'
  activemq:
    broker-url: tcp://127.0.0.1:61616
    user: admin
    password: admin
 